id = "Nubinator/whatpulse-plugin"
name = "Whatpulse (UNOFFICIAL)"
version = "1.0.0"
plugin_api = 4
author = "Nubinator"
license = "MIT"
dependencies = []
tags = ["system", "bar", "panel", "productivity", "utility"]
description = "A quick glance at your whatpulse stats"

[[widget]]
id = "whatpulse"
entry = "widget.luau"

[[service]]
id = "whatpulse-service"
entry = "service.luau"